include:
  - board: nice_nano
    shield: settings_reset
    artifact-name: nano_reset_settings
    
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left_nice_view
  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right_nice_view
