include:
  - board: nice_nano
    shield: settings_reset
    artifact-name: nano_reset_settings
    
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
